[project]
name = "dive_ai"
version = "0.0.1"
dependencies = [
    'jupyter_ai',
]

[project.entry-points."jupyter_ai.model_providers"]
chat-diveai-provider = "diveai_provider:ChatDIVEAIProvider"

[project.entry-points."jupyter_ai.embeddings_model_providers"]
diveai-embeddings-provider = "diveai_provider:DIVEAIEmbeddingsProvider"