{{- if .Values.credentials -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vllm.fullname" . }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.credentials.OPENAI_API_KEY | b64enc | quote }}
{{- end }}