{{- if and .Values.networkPolicy.enabled -}}
{{- $fullName := include "vllm.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "vllm.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  # Read more at: https://kubernetes.io/docs/concepts/services-networking/network-policies/#behavior-of-to-and-from-selectors
  ingress:
    {{- with .Values.networkPolicy.ingress }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
{{- end }}
